$schema: "http://json-schema.org/draft-06/schema#"
description: "general configure settings."
properties:
  fastq_dir:
    default: "by_samples_fastq"
    description: "path to the raw fastq files"
    type: string
  link_table:
    default: "/d0/data/ucsd/refs/links.txt"
    description: "path to the link table - link sampleID with libID"
    type: string
  assay_type:
    default: "snare_2"
    description: "assay type, e.g. 10X, snare_2"
    type: string
  fastqc_dir:
    default: "/home/qiwenhu/software/FastQC/fastqc"
    description: "path to fastqc"
    type: string
  dropest_config:
    default: "/home/qiwenhu/hubmap/pip/scripts/test_script/integrated/conf/split_seq.xml"
    description: "configure file from dropest"
    type: string
  index_file:
    default: "/d0/data/ucsd/refs/refdata-cellranger-GRCh38-3.0.0/star"
    description: "path to STAR index file for alignment"
    type: string
  gtf_dir:
    default: "/d0/data/ucsd/refs/refdata-cellranger-GRCh38-3.0.0/genes/genes.gtf"
    description: "path to gtf file for gene annotation"
    type: string
  genome_mmi:
    default: "/d0/data/ucsd/refs/refdata-cellranger-atac-GRCh38-1.1.0/fasta/genome.fa.mmi"
    description: "path to minimap genome index file for atac alignment"
    type: string
  hs_csize:
    default: "/d0/data/ucsd/refs/refdata-cellranger-atac-GRCh38-1.1.0/fasta/genome.fa.fai"
    description: "path to genome index file"
    type: string
  genome_name:
    default: "hg38"
    description: "genome version"
    type: string
  snap_aligner:
    default: "/home/qiwenhu/software/minimap2"
    description: "path to aligner tools for snaptools"
    type: string
  white_list:
    default: "/home/qiwenhu/hubmap/pip/scripts/test_script/integrated/conf/whitelist"
    description: "whitelist file"
    type: string
  scripts_dir:
    default: "/home/qiwenhu/software/snarePip/scripts"
    description: "path to other scripts needed for processing pipeline"
    type: string
  macs:
    default: "/home/qiwenhu/anaconda2/envs/py36/envs/snakemake/bin/macs2"
    description: "path to macs"
    type: string
  bedtools:
    default: "/home/qiwenhu/software/bedtools2/bin/bedtools"
    description: "path to bedtools"
    type: string
  blacklist:
    default: "/d0/data/ucsd/refs/hg38.blacklist.bed"
    description: "blacklist file"
    type: string
  rna_path:
    default: "/home/qiwenhu/hubmap/pip/test_datasets/samples/RNA_processed_dataset"
    description: "path to processed RNA samples"
    type: string
  dt_n6:
    default: "/d0/data/ucsd/refs/R1_dTN6_pairs.txt"
    description: "txt file contains dt/n6 pairs"
    type: string
  mt_list:
    default: "/home/qiwenhu/software/snarePip/conf/MT_gene.list"
    description: "path to mitochondria gene list"
    type: string
  samtool_path:
    default: "/home/qiwenhu/bin/bin/samtools"
    description: "path to samtools"
    type: string
  scrublet_path:
    default: "/home/qiwenhu/anaconda2/envs/py36/envs/snakemake/bin/python"
    description: "python path for scrublet/doubletDection"
    type: string


