# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_multiply <- function(M1, M2) {
    .Call('_snarePip_fast_multiply', PACKAGE = 'snarePip', M1, M2)
}

